fonts = [
    "Times New Roman",
    "Arial",
    "Courier",
    "Palatino Linotype",
    "Tahoma",
    "Trebuchet MS",
    "Lucida Grande",
    "Courier New",
    "Lucida Console",
    "Consolas",
    "Monaco",
    "Comic Sans MS",
    "Brush Script MT",
    "Impact",
    "Papyrus",
    "Jokerman",
    "Arial",
    "Times New Roman",
    "Calibri",
    "Cambria",
    "Segoe UI"
    "Helvetica",
    "Avenir",
    "Georgia",
    "Menlo",
    "DejaVu Sans",
    "Liberation Sans",
    "FreeMono",
]
